// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocessor.proto

#ifndef PROTOBUF_coprocessor_2eproto__INCLUDED
#define PROTOBUF_coprocessor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "errorpb.pb.h"
#include "kvrpcpb.pb.h"
// @@protoc_insertion_point(includes)

namespace coprocessor {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_coprocessor_2eproto();
void protobuf_AssignDesc_coprocessor_2eproto();
void protobuf_ShutdownFile_coprocessor_2eproto();

class KeyRange;
class Request;
class Response;

// ===================================================================

class KeyRange : public ::google::protobuf::Message {
 public:
  KeyRange();
  virtual ~KeyRange();

  KeyRange(const KeyRange& from);

  inline KeyRange& operator=(const KeyRange& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyRange& default_instance();

  void Swap(KeyRange* other);

  // implements Message ----------------------------------------------

  KeyRange* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeyRange& from);
  void MergeFrom(const KeyRange& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes start = 1;
  inline bool has_start() const;
  inline void clear_start();
  static const int kStartFieldNumber = 1;
  inline const ::std::string& start() const;
  inline void set_start(const ::std::string& value);
  inline void set_start(const char* value);
  inline void set_start(const void* value, size_t size);
  inline ::std::string* mutable_start();
  inline ::std::string* release_start();
  inline void set_allocated_start(::std::string* start);

  // optional bytes end = 2;
  inline bool has_end() const;
  inline void clear_end();
  static const int kEndFieldNumber = 2;
  inline const ::std::string& end() const;
  inline void set_end(const ::std::string& value);
  inline void set_end(const char* value);
  inline void set_end(const void* value, size_t size);
  inline ::std::string* mutable_end();
  inline ::std::string* release_end();
  inline void set_allocated_end(::std::string* end);

  // @@protoc_insertion_point(class_scope:coprocessor.KeyRange)
 private:
  inline void set_has_start();
  inline void clear_has_start();
  inline void set_has_end();
  inline void clear_has_end();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* start_;
  ::std::string* end_;
  friend void  protobuf_AddDesc_coprocessor_2eproto();
  friend void protobuf_AssignDesc_coprocessor_2eproto();
  friend void protobuf_ShutdownFile_coprocessor_2eproto();

  void InitAsDefaultInstance();
  static KeyRange* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .kvrpcpb.Context context = 1;
  inline bool has_context() const;
  inline void clear_context();
  static const int kContextFieldNumber = 1;
  inline const ::kvrpcpb::Context& context() const;
  inline ::kvrpcpb::Context* mutable_context();
  inline ::kvrpcpb::Context* release_context();
  inline void set_allocated_context(::kvrpcpb::Context* context);

  // optional int64 tp = 2;
  inline bool has_tp() const;
  inline void clear_tp();
  static const int kTpFieldNumber = 2;
  inline ::google::protobuf::int64 tp() const;
  inline void set_tp(::google::protobuf::int64 value);

  // optional bytes data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // repeated .coprocessor.KeyRange ranges = 4;
  inline int ranges_size() const;
  inline void clear_ranges();
  static const int kRangesFieldNumber = 4;
  inline const ::coprocessor::KeyRange& ranges(int index) const;
  inline ::coprocessor::KeyRange* mutable_ranges(int index);
  inline ::coprocessor::KeyRange* add_ranges();
  inline const ::google::protobuf::RepeatedPtrField< ::coprocessor::KeyRange >&
      ranges() const;
  inline ::google::protobuf::RepeatedPtrField< ::coprocessor::KeyRange >*
      mutable_ranges();

  // @@protoc_insertion_point(class_scope:coprocessor.Request)
 private:
  inline void set_has_context();
  inline void clear_has_context();
  inline void set_has_tp();
  inline void clear_has_tp();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::kvrpcpb::Context* context_;
  ::google::protobuf::int64 tp_;
  ::std::string* data_;
  ::google::protobuf::RepeatedPtrField< ::coprocessor::KeyRange > ranges_;
  friend void  protobuf_AddDesc_coprocessor_2eproto();
  friend void protobuf_AssignDesc_coprocessor_2eproto();
  friend void protobuf_ShutdownFile_coprocessor_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional .errorpb.Error region_error = 2;
  inline bool has_region_error() const;
  inline void clear_region_error();
  static const int kRegionErrorFieldNumber = 2;
  inline const ::errorpb::Error& region_error() const;
  inline ::errorpb::Error* mutable_region_error();
  inline ::errorpb::Error* release_region_error();
  inline void set_allocated_region_error(::errorpb::Error* region_error);

  // optional .kvrpcpb.LockInfo locked = 3;
  inline bool has_locked() const;
  inline void clear_locked();
  static const int kLockedFieldNumber = 3;
  inline const ::kvrpcpb::LockInfo& locked() const;
  inline ::kvrpcpb::LockInfo* mutable_locked();
  inline ::kvrpcpb::LockInfo* release_locked();
  inline void set_allocated_locked(::kvrpcpb::LockInfo* locked);

  // optional string other_error = 4;
  inline bool has_other_error() const;
  inline void clear_other_error();
  static const int kOtherErrorFieldNumber = 4;
  inline const ::std::string& other_error() const;
  inline void set_other_error(const ::std::string& value);
  inline void set_other_error(const char* value);
  inline void set_other_error(const char* value, size_t size);
  inline ::std::string* mutable_other_error();
  inline ::std::string* release_other_error();
  inline void set_allocated_other_error(::std::string* other_error);

  // @@protoc_insertion_point(class_scope:coprocessor.Response)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_region_error();
  inline void clear_has_region_error();
  inline void set_has_locked();
  inline void clear_has_locked();
  inline void set_has_other_error();
  inline void clear_has_other_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::errorpb::Error* region_error_;
  ::kvrpcpb::LockInfo* locked_;
  ::std::string* other_error_;
  friend void  protobuf_AddDesc_coprocessor_2eproto();
  friend void protobuf_AssignDesc_coprocessor_2eproto();
  friend void protobuf_ShutdownFile_coprocessor_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// ===================================================================


// ===================================================================

// KeyRange

// optional bytes start = 1;
inline bool KeyRange::has_start() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KeyRange::set_has_start() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KeyRange::clear_has_start() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KeyRange::clear_start() {
  if (start_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_->clear();
  }
  clear_has_start();
}
inline const ::std::string& KeyRange::start() const {
  // @@protoc_insertion_point(field_get:coprocessor.KeyRange.start)
  return *start_;
}
inline void KeyRange::set_start(const ::std::string& value) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(value);
  // @@protoc_insertion_point(field_set:coprocessor.KeyRange.start)
}
inline void KeyRange::set_start(const char* value) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocessor.KeyRange.start)
}
inline void KeyRange::set_start(const void* value, size_t size) {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  start_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocessor.KeyRange.start)
}
inline ::std::string* KeyRange::mutable_start() {
  set_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.KeyRange.start)
  return start_;
}
inline ::std::string* KeyRange::release_start() {
  clear_has_start();
  if (start_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = start_;
    start_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void KeyRange::set_allocated_start(::std::string* start) {
  if (start_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete start_;
  }
  if (start) {
    set_has_start();
    start_ = start;
  } else {
    clear_has_start();
    start_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.KeyRange.start)
}

// optional bytes end = 2;
inline bool KeyRange::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KeyRange::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void KeyRange::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void KeyRange::clear_end() {
  if (end_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_->clear();
  }
  clear_has_end();
}
inline const ::std::string& KeyRange::end() const {
  // @@protoc_insertion_point(field_get:coprocessor.KeyRange.end)
  return *end_;
}
inline void KeyRange::set_end(const ::std::string& value) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(value);
  // @@protoc_insertion_point(field_set:coprocessor.KeyRange.end)
}
inline void KeyRange::set_end(const char* value) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocessor.KeyRange.end)
}
inline void KeyRange::set_end(const void* value, size_t size) {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  end_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocessor.KeyRange.end)
}
inline ::std::string* KeyRange::mutable_end() {
  set_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.KeyRange.end)
  return end_;
}
inline ::std::string* KeyRange::release_end() {
  clear_has_end();
  if (end_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = end_;
    end_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void KeyRange::set_allocated_end(::std::string* end) {
  if (end_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete end_;
  }
  if (end) {
    set_has_end();
    end_ = end;
  } else {
    clear_has_end();
    end_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.KeyRange.end)
}

// -------------------------------------------------------------------

// Request

// optional .kvrpcpb.Context context = 1;
inline bool Request::has_context() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_context() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_context() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_context() {
  if (context_ != NULL) context_->::kvrpcpb::Context::Clear();
  clear_has_context();
}
inline const ::kvrpcpb::Context& Request::context() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.context)
  return context_ != NULL ? *context_ : *default_instance_->context_;
}
inline ::kvrpcpb::Context* Request::mutable_context() {
  set_has_context();
  if (context_ == NULL) context_ = new ::kvrpcpb::Context;
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.context)
  return context_;
}
inline ::kvrpcpb::Context* Request::release_context() {
  clear_has_context();
  ::kvrpcpb::Context* temp = context_;
  context_ = NULL;
  return temp;
}
inline void Request::set_allocated_context(::kvrpcpb::Context* context) {
  delete context_;
  context_ = context;
  if (context) {
    set_has_context();
  } else {
    clear_has_context();
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Request.context)
}

// optional int64 tp = 2;
inline bool Request::has_tp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_tp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_tp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_tp() {
  tp_ = GOOGLE_LONGLONG(0);
  clear_has_tp();
}
inline ::google::protobuf::int64 Request::tp() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.tp)
  return tp_;
}
inline void Request::set_tp(::google::protobuf::int64 value) {
  set_has_tp();
  tp_ = value;
  // @@protoc_insertion_point(field_set:coprocessor.Request.tp)
}

// optional bytes data = 3;
inline bool Request::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Request::data() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.data)
  return *data_;
}
inline void Request::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:coprocessor.Request.data)
}
inline void Request::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocessor.Request.data)
}
inline void Request::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Request.data)
}
inline ::std::string* Request::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.data)
  return data_;
}
inline ::std::string* Request::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Request::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Request.data)
}

// repeated .coprocessor.KeyRange ranges = 4;
inline int Request::ranges_size() const {
  return ranges_.size();
}
inline void Request::clear_ranges() {
  ranges_.Clear();
}
inline const ::coprocessor::KeyRange& Request::ranges(int index) const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.ranges)
  return ranges_.Get(index);
}
inline ::coprocessor::KeyRange* Request::mutable_ranges(int index) {
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.ranges)
  return ranges_.Mutable(index);
}
inline ::coprocessor::KeyRange* Request::add_ranges() {
  // @@protoc_insertion_point(field_add:coprocessor.Request.ranges)
  return ranges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::coprocessor::KeyRange >&
Request::ranges() const {
  // @@protoc_insertion_point(field_list:coprocessor.Request.ranges)
  return ranges_;
}
inline ::google::protobuf::RepeatedPtrField< ::coprocessor::KeyRange >*
Request::mutable_ranges() {
  // @@protoc_insertion_point(field_mutable_list:coprocessor.Request.ranges)
  return &ranges_;
}

// -------------------------------------------------------------------

// Response

// optional bytes data = 1;
inline bool Response::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Response::data() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.data)
  return *data_;
}
inline void Response::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:coprocessor.Response.data)
}
inline void Response::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocessor.Response.data)
}
inline void Response::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Response.data)
}
inline ::std::string* Response::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.data)
  return data_;
}
inline ::std::string* Response::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Response::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.data)
}

// optional .errorpb.Error region_error = 2;
inline bool Response::has_region_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_region_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_region_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_region_error() {
  if (region_error_ != NULL) region_error_->::errorpb::Error::Clear();
  clear_has_region_error();
}
inline const ::errorpb::Error& Response::region_error() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.region_error)
  return region_error_ != NULL ? *region_error_ : *default_instance_->region_error_;
}
inline ::errorpb::Error* Response::mutable_region_error() {
  set_has_region_error();
  if (region_error_ == NULL) region_error_ = new ::errorpb::Error;
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.region_error)
  return region_error_;
}
inline ::errorpb::Error* Response::release_region_error() {
  clear_has_region_error();
  ::errorpb::Error* temp = region_error_;
  region_error_ = NULL;
  return temp;
}
inline void Response::set_allocated_region_error(::errorpb::Error* region_error) {
  delete region_error_;
  region_error_ = region_error;
  if (region_error) {
    set_has_region_error();
  } else {
    clear_has_region_error();
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.region_error)
}

// optional .kvrpcpb.LockInfo locked = 3;
inline bool Response::has_locked() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_locked() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_locked() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_locked() {
  if (locked_ != NULL) locked_->::kvrpcpb::LockInfo::Clear();
  clear_has_locked();
}
inline const ::kvrpcpb::LockInfo& Response::locked() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.locked)
  return locked_ != NULL ? *locked_ : *default_instance_->locked_;
}
inline ::kvrpcpb::LockInfo* Response::mutable_locked() {
  set_has_locked();
  if (locked_ == NULL) locked_ = new ::kvrpcpb::LockInfo;
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.locked)
  return locked_;
}
inline ::kvrpcpb::LockInfo* Response::release_locked() {
  clear_has_locked();
  ::kvrpcpb::LockInfo* temp = locked_;
  locked_ = NULL;
  return temp;
}
inline void Response::set_allocated_locked(::kvrpcpb::LockInfo* locked) {
  delete locked_;
  locked_ = locked;
  if (locked) {
    set_has_locked();
  } else {
    clear_has_locked();
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.locked)
}

// optional string other_error = 4;
inline bool Response::has_other_error() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_other_error() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_other_error() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_other_error() {
  if (other_error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    other_error_->clear();
  }
  clear_has_other_error();
}
inline const ::std::string& Response::other_error() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.other_error)
  return *other_error_;
}
inline void Response::set_other_error(const ::std::string& value) {
  set_has_other_error();
  if (other_error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    other_error_ = new ::std::string;
  }
  other_error_->assign(value);
  // @@protoc_insertion_point(field_set:coprocessor.Response.other_error)
}
inline void Response::set_other_error(const char* value) {
  set_has_other_error();
  if (other_error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    other_error_ = new ::std::string;
  }
  other_error_->assign(value);
  // @@protoc_insertion_point(field_set_char:coprocessor.Response.other_error)
}
inline void Response::set_other_error(const char* value, size_t size) {
  set_has_other_error();
  if (other_error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    other_error_ = new ::std::string;
  }
  other_error_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Response.other_error)
}
inline ::std::string* Response::mutable_other_error() {
  set_has_other_error();
  if (other_error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    other_error_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.other_error)
  return other_error_;
}
inline ::std::string* Response::release_other_error() {
  clear_has_other_error();
  if (other_error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = other_error_;
    other_error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Response::set_allocated_other_error(::std::string* other_error) {
  if (other_error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete other_error_;
  }
  if (other_error) {
    set_has_other_error();
    other_error_ = other_error;
  } else {
    clear_has_other_error();
    other_error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.other_error)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocessor

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_coprocessor_2eproto__INCLUDED
