// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errorpb.proto

#ifndef PROTOBUF_errorpb_2eproto__INCLUDED
#define PROTOBUF_errorpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "metapb.pb.h"
// @@protoc_insertion_point(includes)

namespace errorpb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_errorpb_2eproto();
void protobuf_AssignDesc_errorpb_2eproto();
void protobuf_ShutdownFile_errorpb_2eproto();

class NotLeader;
class StoreNotMatch;
class RegionNotFound;
class KeyNotInRegion;
class StaleEpoch;
class ServerIsBusy;
class StaleCommand;
class RaftEntryTooLarge;
class Error;

// ===================================================================

class NotLeader : public ::google::protobuf::Message {
 public:
  NotLeader();
  virtual ~NotLeader();

  NotLeader(const NotLeader& from);

  inline NotLeader& operator=(const NotLeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NotLeader& default_instance();

  void Swap(NotLeader* other);

  // implements Message ----------------------------------------------

  NotLeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NotLeader& from);
  void MergeFrom(const NotLeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 region_id = 1;
  inline bool has_region_id() const;
  inline void clear_region_id();
  static const int kRegionIdFieldNumber = 1;
  inline ::google::protobuf::uint64 region_id() const;
  inline void set_region_id(::google::protobuf::uint64 value);

  // optional .metapb.Peer leader = 2;
  inline bool has_leader() const;
  inline void clear_leader();
  static const int kLeaderFieldNumber = 2;
  inline const ::metapb::Peer& leader() const;
  inline ::metapb::Peer* mutable_leader();
  inline ::metapb::Peer* release_leader();
  inline void set_allocated_leader(::metapb::Peer* leader);

  // @@protoc_insertion_point(class_scope:errorpb.NotLeader)
 private:
  inline void set_has_region_id();
  inline void clear_has_region_id();
  inline void set_has_leader();
  inline void clear_has_leader();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 region_id_;
  ::metapb::Peer* leader_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static NotLeader* default_instance_;
};
// -------------------------------------------------------------------

class StoreNotMatch : public ::google::protobuf::Message {
 public:
  StoreNotMatch();
  virtual ~StoreNotMatch();

  StoreNotMatch(const StoreNotMatch& from);

  inline StoreNotMatch& operator=(const StoreNotMatch& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StoreNotMatch& default_instance();

  void Swap(StoreNotMatch* other);

  // implements Message ----------------------------------------------

  StoreNotMatch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StoreNotMatch& from);
  void MergeFrom(const StoreNotMatch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:errorpb.StoreNotMatch)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static StoreNotMatch* default_instance_;
};
// -------------------------------------------------------------------

class RegionNotFound : public ::google::protobuf::Message {
 public:
  RegionNotFound();
  virtual ~RegionNotFound();

  RegionNotFound(const RegionNotFound& from);

  inline RegionNotFound& operator=(const RegionNotFound& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegionNotFound& default_instance();

  void Swap(RegionNotFound* other);

  // implements Message ----------------------------------------------

  RegionNotFound* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegionNotFound& from);
  void MergeFrom(const RegionNotFound& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 region_id = 1;
  inline bool has_region_id() const;
  inline void clear_region_id();
  static const int kRegionIdFieldNumber = 1;
  inline ::google::protobuf::uint64 region_id() const;
  inline void set_region_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:errorpb.RegionNotFound)
 private:
  inline void set_has_region_id();
  inline void clear_has_region_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 region_id_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static RegionNotFound* default_instance_;
};
// -------------------------------------------------------------------

class KeyNotInRegion : public ::google::protobuf::Message {
 public:
  KeyNotInRegion();
  virtual ~KeyNotInRegion();

  KeyNotInRegion(const KeyNotInRegion& from);

  inline KeyNotInRegion& operator=(const KeyNotInRegion& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyNotInRegion& default_instance();

  void Swap(KeyNotInRegion* other);

  // implements Message ----------------------------------------------

  KeyNotInRegion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeyNotInRegion& from);
  void MergeFrom(const KeyNotInRegion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes key = 1;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const void* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // optional uint64 region_id = 2;
  inline bool has_region_id() const;
  inline void clear_region_id();
  static const int kRegionIdFieldNumber = 2;
  inline ::google::protobuf::uint64 region_id() const;
  inline void set_region_id(::google::protobuf::uint64 value);

  // optional bytes start_key = 3;
  inline bool has_start_key() const;
  inline void clear_start_key();
  static const int kStartKeyFieldNumber = 3;
  inline const ::std::string& start_key() const;
  inline void set_start_key(const ::std::string& value);
  inline void set_start_key(const char* value);
  inline void set_start_key(const void* value, size_t size);
  inline ::std::string* mutable_start_key();
  inline ::std::string* release_start_key();
  inline void set_allocated_start_key(::std::string* start_key);

  // optional bytes end_key = 4;
  inline bool has_end_key() const;
  inline void clear_end_key();
  static const int kEndKeyFieldNumber = 4;
  inline const ::std::string& end_key() const;
  inline void set_end_key(const ::std::string& value);
  inline void set_end_key(const char* value);
  inline void set_end_key(const void* value, size_t size);
  inline ::std::string* mutable_end_key();
  inline ::std::string* release_end_key();
  inline void set_allocated_end_key(::std::string* end_key);

  // @@protoc_insertion_point(class_scope:errorpb.KeyNotInRegion)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_region_id();
  inline void clear_has_region_id();
  inline void set_has_start_key();
  inline void clear_has_start_key();
  inline void set_has_end_key();
  inline void clear_has_end_key();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* key_;
  ::google::protobuf::uint64 region_id_;
  ::std::string* start_key_;
  ::std::string* end_key_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static KeyNotInRegion* default_instance_;
};
// -------------------------------------------------------------------

class StaleEpoch : public ::google::protobuf::Message {
 public:
  StaleEpoch();
  virtual ~StaleEpoch();

  StaleEpoch(const StaleEpoch& from);

  inline StaleEpoch& operator=(const StaleEpoch& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StaleEpoch& default_instance();

  void Swap(StaleEpoch* other);

  // implements Message ----------------------------------------------

  StaleEpoch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StaleEpoch& from);
  void MergeFrom(const StaleEpoch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .metapb.Region new_regions = 1;
  inline int new_regions_size() const;
  inline void clear_new_regions();
  static const int kNewRegionsFieldNumber = 1;
  inline const ::metapb::Region& new_regions(int index) const;
  inline ::metapb::Region* mutable_new_regions(int index);
  inline ::metapb::Region* add_new_regions();
  inline const ::google::protobuf::RepeatedPtrField< ::metapb::Region >&
      new_regions() const;
  inline ::google::protobuf::RepeatedPtrField< ::metapb::Region >*
      mutable_new_regions();

  // @@protoc_insertion_point(class_scope:errorpb.StaleEpoch)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::metapb::Region > new_regions_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static StaleEpoch* default_instance_;
};
// -------------------------------------------------------------------

class ServerIsBusy : public ::google::protobuf::Message {
 public:
  ServerIsBusy();
  virtual ~ServerIsBusy();

  ServerIsBusy(const ServerIsBusy& from);

  inline ServerIsBusy& operator=(const ServerIsBusy& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerIsBusy& default_instance();

  void Swap(ServerIsBusy* other);

  // implements Message ----------------------------------------------

  ServerIsBusy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerIsBusy& from);
  void MergeFrom(const ServerIsBusy& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:errorpb.ServerIsBusy)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static ServerIsBusy* default_instance_;
};
// -------------------------------------------------------------------

class StaleCommand : public ::google::protobuf::Message {
 public:
  StaleCommand();
  virtual ~StaleCommand();

  StaleCommand(const StaleCommand& from);

  inline StaleCommand& operator=(const StaleCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StaleCommand& default_instance();

  void Swap(StaleCommand* other);

  // implements Message ----------------------------------------------

  StaleCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StaleCommand& from);
  void MergeFrom(const StaleCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:errorpb.StaleCommand)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static StaleCommand* default_instance_;
};
// -------------------------------------------------------------------

class RaftEntryTooLarge : public ::google::protobuf::Message {
 public:
  RaftEntryTooLarge();
  virtual ~RaftEntryTooLarge();

  RaftEntryTooLarge(const RaftEntryTooLarge& from);

  inline RaftEntryTooLarge& operator=(const RaftEntryTooLarge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftEntryTooLarge& default_instance();

  void Swap(RaftEntryTooLarge* other);

  // implements Message ----------------------------------------------

  RaftEntryTooLarge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RaftEntryTooLarge& from);
  void MergeFrom(const RaftEntryTooLarge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 region_id = 1;
  inline bool has_region_id() const;
  inline void clear_region_id();
  static const int kRegionIdFieldNumber = 1;
  inline ::google::protobuf::uint64 region_id() const;
  inline void set_region_id(::google::protobuf::uint64 value);

  // optional uint64 entry_size = 2;
  inline bool has_entry_size() const;
  inline void clear_entry_size();
  static const int kEntrySizeFieldNumber = 2;
  inline ::google::protobuf::uint64 entry_size() const;
  inline void set_entry_size(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:errorpb.RaftEntryTooLarge)
 private:
  inline void set_has_region_id();
  inline void clear_has_region_id();
  inline void set_has_entry_size();
  inline void clear_has_entry_size();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 region_id_;
  ::google::protobuf::uint64 entry_size_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static RaftEntryTooLarge* default_instance_;
};
// -------------------------------------------------------------------

class Error : public ::google::protobuf::Message {
 public:
  Error();
  virtual ~Error();

  Error(const Error& from);

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Error& default_instance();

  void Swap(Error* other);

  // implements Message ----------------------------------------------

  Error* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Error& from);
  void MergeFrom(const Error& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string message = 1;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 1;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional .errorpb.NotLeader not_leader = 2;
  inline bool has_not_leader() const;
  inline void clear_not_leader();
  static const int kNotLeaderFieldNumber = 2;
  inline const ::errorpb::NotLeader& not_leader() const;
  inline ::errorpb::NotLeader* mutable_not_leader();
  inline ::errorpb::NotLeader* release_not_leader();
  inline void set_allocated_not_leader(::errorpb::NotLeader* not_leader);

  // optional .errorpb.RegionNotFound region_not_found = 3;
  inline bool has_region_not_found() const;
  inline void clear_region_not_found();
  static const int kRegionNotFoundFieldNumber = 3;
  inline const ::errorpb::RegionNotFound& region_not_found() const;
  inline ::errorpb::RegionNotFound* mutable_region_not_found();
  inline ::errorpb::RegionNotFound* release_region_not_found();
  inline void set_allocated_region_not_found(::errorpb::RegionNotFound* region_not_found);

  // optional .errorpb.KeyNotInRegion key_not_in_region = 4;
  inline bool has_key_not_in_region() const;
  inline void clear_key_not_in_region();
  static const int kKeyNotInRegionFieldNumber = 4;
  inline const ::errorpb::KeyNotInRegion& key_not_in_region() const;
  inline ::errorpb::KeyNotInRegion* mutable_key_not_in_region();
  inline ::errorpb::KeyNotInRegion* release_key_not_in_region();
  inline void set_allocated_key_not_in_region(::errorpb::KeyNotInRegion* key_not_in_region);

  // optional .errorpb.StaleEpoch stale_epoch = 5;
  inline bool has_stale_epoch() const;
  inline void clear_stale_epoch();
  static const int kStaleEpochFieldNumber = 5;
  inline const ::errorpb::StaleEpoch& stale_epoch() const;
  inline ::errorpb::StaleEpoch* mutable_stale_epoch();
  inline ::errorpb::StaleEpoch* release_stale_epoch();
  inline void set_allocated_stale_epoch(::errorpb::StaleEpoch* stale_epoch);

  // optional .errorpb.ServerIsBusy server_is_busy = 6;
  inline bool has_server_is_busy() const;
  inline void clear_server_is_busy();
  static const int kServerIsBusyFieldNumber = 6;
  inline const ::errorpb::ServerIsBusy& server_is_busy() const;
  inline ::errorpb::ServerIsBusy* mutable_server_is_busy();
  inline ::errorpb::ServerIsBusy* release_server_is_busy();
  inline void set_allocated_server_is_busy(::errorpb::ServerIsBusy* server_is_busy);

  // optional .errorpb.StaleCommand stale_command = 7;
  inline bool has_stale_command() const;
  inline void clear_stale_command();
  static const int kStaleCommandFieldNumber = 7;
  inline const ::errorpb::StaleCommand& stale_command() const;
  inline ::errorpb::StaleCommand* mutable_stale_command();
  inline ::errorpb::StaleCommand* release_stale_command();
  inline void set_allocated_stale_command(::errorpb::StaleCommand* stale_command);

  // optional .errorpb.StoreNotMatch store_not_match = 8;
  inline bool has_store_not_match() const;
  inline void clear_store_not_match();
  static const int kStoreNotMatchFieldNumber = 8;
  inline const ::errorpb::StoreNotMatch& store_not_match() const;
  inline ::errorpb::StoreNotMatch* mutable_store_not_match();
  inline ::errorpb::StoreNotMatch* release_store_not_match();
  inline void set_allocated_store_not_match(::errorpb::StoreNotMatch* store_not_match);

  // optional .errorpb.RaftEntryTooLarge raft_entry_too_large = 9;
  inline bool has_raft_entry_too_large() const;
  inline void clear_raft_entry_too_large();
  static const int kRaftEntryTooLargeFieldNumber = 9;
  inline const ::errorpb::RaftEntryTooLarge& raft_entry_too_large() const;
  inline ::errorpb::RaftEntryTooLarge* mutable_raft_entry_too_large();
  inline ::errorpb::RaftEntryTooLarge* release_raft_entry_too_large();
  inline void set_allocated_raft_entry_too_large(::errorpb::RaftEntryTooLarge* raft_entry_too_large);

  // @@protoc_insertion_point(class_scope:errorpb.Error)
 private:
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_not_leader();
  inline void clear_has_not_leader();
  inline void set_has_region_not_found();
  inline void clear_has_region_not_found();
  inline void set_has_key_not_in_region();
  inline void clear_has_key_not_in_region();
  inline void set_has_stale_epoch();
  inline void clear_has_stale_epoch();
  inline void set_has_server_is_busy();
  inline void clear_has_server_is_busy();
  inline void set_has_stale_command();
  inline void clear_has_stale_command();
  inline void set_has_store_not_match();
  inline void clear_has_store_not_match();
  inline void set_has_raft_entry_too_large();
  inline void clear_has_raft_entry_too_large();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* message_;
  ::errorpb::NotLeader* not_leader_;
  ::errorpb::RegionNotFound* region_not_found_;
  ::errorpb::KeyNotInRegion* key_not_in_region_;
  ::errorpb::StaleEpoch* stale_epoch_;
  ::errorpb::ServerIsBusy* server_is_busy_;
  ::errorpb::StaleCommand* stale_command_;
  ::errorpb::StoreNotMatch* store_not_match_;
  ::errorpb::RaftEntryTooLarge* raft_entry_too_large_;
  friend void  protobuf_AddDesc_errorpb_2eproto();
  friend void protobuf_AssignDesc_errorpb_2eproto();
  friend void protobuf_ShutdownFile_errorpb_2eproto();

  void InitAsDefaultInstance();
  static Error* default_instance_;
};
// ===================================================================


// ===================================================================

// NotLeader

// optional uint64 region_id = 1;
inline bool NotLeader::has_region_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NotLeader::set_has_region_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NotLeader::clear_has_region_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NotLeader::clear_region_id() {
  region_id_ = GOOGLE_ULONGLONG(0);
  clear_has_region_id();
}
inline ::google::protobuf::uint64 NotLeader::region_id() const {
  // @@protoc_insertion_point(field_get:errorpb.NotLeader.region_id)
  return region_id_;
}
inline void NotLeader::set_region_id(::google::protobuf::uint64 value) {
  set_has_region_id();
  region_id_ = value;
  // @@protoc_insertion_point(field_set:errorpb.NotLeader.region_id)
}

// optional .metapb.Peer leader = 2;
inline bool NotLeader::has_leader() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NotLeader::set_has_leader() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NotLeader::clear_has_leader() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NotLeader::clear_leader() {
  if (leader_ != NULL) leader_->::metapb::Peer::Clear();
  clear_has_leader();
}
inline const ::metapb::Peer& NotLeader::leader() const {
  // @@protoc_insertion_point(field_get:errorpb.NotLeader.leader)
  return leader_ != NULL ? *leader_ : *default_instance_->leader_;
}
inline ::metapb::Peer* NotLeader::mutable_leader() {
  set_has_leader();
  if (leader_ == NULL) leader_ = new ::metapb::Peer;
  // @@protoc_insertion_point(field_mutable:errorpb.NotLeader.leader)
  return leader_;
}
inline ::metapb::Peer* NotLeader::release_leader() {
  clear_has_leader();
  ::metapb::Peer* temp = leader_;
  leader_ = NULL;
  return temp;
}
inline void NotLeader::set_allocated_leader(::metapb::Peer* leader) {
  delete leader_;
  leader_ = leader;
  if (leader) {
    set_has_leader();
  } else {
    clear_has_leader();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.NotLeader.leader)
}

// -------------------------------------------------------------------

// StoreNotMatch

// -------------------------------------------------------------------

// RegionNotFound

// optional uint64 region_id = 1;
inline bool RegionNotFound::has_region_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegionNotFound::set_has_region_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegionNotFound::clear_has_region_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegionNotFound::clear_region_id() {
  region_id_ = GOOGLE_ULONGLONG(0);
  clear_has_region_id();
}
inline ::google::protobuf::uint64 RegionNotFound::region_id() const {
  // @@protoc_insertion_point(field_get:errorpb.RegionNotFound.region_id)
  return region_id_;
}
inline void RegionNotFound::set_region_id(::google::protobuf::uint64 value) {
  set_has_region_id();
  region_id_ = value;
  // @@protoc_insertion_point(field_set:errorpb.RegionNotFound.region_id)
}

// -------------------------------------------------------------------

// KeyNotInRegion

// optional bytes key = 1;
inline bool KeyNotInRegion::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void KeyNotInRegion::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void KeyNotInRegion::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void KeyNotInRegion::clear_key() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& KeyNotInRegion::key() const {
  // @@protoc_insertion_point(field_get:errorpb.KeyNotInRegion.key)
  return *key_;
}
inline void KeyNotInRegion::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set:errorpb.KeyNotInRegion.key)
}
inline void KeyNotInRegion::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(value);
  // @@protoc_insertion_point(field_set_char:errorpb.KeyNotInRegion.key)
}
inline void KeyNotInRegion::set_key(const void* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:errorpb.KeyNotInRegion.key)
}
inline ::std::string* KeyNotInRegion::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    key_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:errorpb.KeyNotInRegion.key)
  return key_;
}
inline ::std::string* KeyNotInRegion::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void KeyNotInRegion::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.KeyNotInRegion.key)
}

// optional uint64 region_id = 2;
inline bool KeyNotInRegion::has_region_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void KeyNotInRegion::set_has_region_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void KeyNotInRegion::clear_has_region_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void KeyNotInRegion::clear_region_id() {
  region_id_ = GOOGLE_ULONGLONG(0);
  clear_has_region_id();
}
inline ::google::protobuf::uint64 KeyNotInRegion::region_id() const {
  // @@protoc_insertion_point(field_get:errorpb.KeyNotInRegion.region_id)
  return region_id_;
}
inline void KeyNotInRegion::set_region_id(::google::protobuf::uint64 value) {
  set_has_region_id();
  region_id_ = value;
  // @@protoc_insertion_point(field_set:errorpb.KeyNotInRegion.region_id)
}

// optional bytes start_key = 3;
inline bool KeyNotInRegion::has_start_key() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void KeyNotInRegion::set_has_start_key() {
  _has_bits_[0] |= 0x00000004u;
}
inline void KeyNotInRegion::clear_has_start_key() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void KeyNotInRegion::clear_start_key() {
  if (start_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_key_->clear();
  }
  clear_has_start_key();
}
inline const ::std::string& KeyNotInRegion::start_key() const {
  // @@protoc_insertion_point(field_get:errorpb.KeyNotInRegion.start_key)
  return *start_key_;
}
inline void KeyNotInRegion::set_start_key(const ::std::string& value) {
  set_has_start_key();
  if (start_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_key_ = new ::std::string;
  }
  start_key_->assign(value);
  // @@protoc_insertion_point(field_set:errorpb.KeyNotInRegion.start_key)
}
inline void KeyNotInRegion::set_start_key(const char* value) {
  set_has_start_key();
  if (start_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_key_ = new ::std::string;
  }
  start_key_->assign(value);
  // @@protoc_insertion_point(field_set_char:errorpb.KeyNotInRegion.start_key)
}
inline void KeyNotInRegion::set_start_key(const void* value, size_t size) {
  set_has_start_key();
  if (start_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_key_ = new ::std::string;
  }
  start_key_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:errorpb.KeyNotInRegion.start_key)
}
inline ::std::string* KeyNotInRegion::mutable_start_key() {
  set_has_start_key();
  if (start_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_key_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:errorpb.KeyNotInRegion.start_key)
  return start_key_;
}
inline ::std::string* KeyNotInRegion::release_start_key() {
  clear_has_start_key();
  if (start_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = start_key_;
    start_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void KeyNotInRegion::set_allocated_start_key(::std::string* start_key) {
  if (start_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete start_key_;
  }
  if (start_key) {
    set_has_start_key();
    start_key_ = start_key;
  } else {
    clear_has_start_key();
    start_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.KeyNotInRegion.start_key)
}

// optional bytes end_key = 4;
inline bool KeyNotInRegion::has_end_key() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void KeyNotInRegion::set_has_end_key() {
  _has_bits_[0] |= 0x00000008u;
}
inline void KeyNotInRegion::clear_has_end_key() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void KeyNotInRegion::clear_end_key() {
  if (end_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_key_->clear();
  }
  clear_has_end_key();
}
inline const ::std::string& KeyNotInRegion::end_key() const {
  // @@protoc_insertion_point(field_get:errorpb.KeyNotInRegion.end_key)
  return *end_key_;
}
inline void KeyNotInRegion::set_end_key(const ::std::string& value) {
  set_has_end_key();
  if (end_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_key_ = new ::std::string;
  }
  end_key_->assign(value);
  // @@protoc_insertion_point(field_set:errorpb.KeyNotInRegion.end_key)
}
inline void KeyNotInRegion::set_end_key(const char* value) {
  set_has_end_key();
  if (end_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_key_ = new ::std::string;
  }
  end_key_->assign(value);
  // @@protoc_insertion_point(field_set_char:errorpb.KeyNotInRegion.end_key)
}
inline void KeyNotInRegion::set_end_key(const void* value, size_t size) {
  set_has_end_key();
  if (end_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_key_ = new ::std::string;
  }
  end_key_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:errorpb.KeyNotInRegion.end_key)
}
inline ::std::string* KeyNotInRegion::mutable_end_key() {
  set_has_end_key();
  if (end_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_key_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:errorpb.KeyNotInRegion.end_key)
  return end_key_;
}
inline ::std::string* KeyNotInRegion::release_end_key() {
  clear_has_end_key();
  if (end_key_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = end_key_;
    end_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void KeyNotInRegion::set_allocated_end_key(::std::string* end_key) {
  if (end_key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete end_key_;
  }
  if (end_key) {
    set_has_end_key();
    end_key_ = end_key;
  } else {
    clear_has_end_key();
    end_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.KeyNotInRegion.end_key)
}

// -------------------------------------------------------------------

// StaleEpoch

// repeated .metapb.Region new_regions = 1;
inline int StaleEpoch::new_regions_size() const {
  return new_regions_.size();
}
inline void StaleEpoch::clear_new_regions() {
  new_regions_.Clear();
}
inline const ::metapb::Region& StaleEpoch::new_regions(int index) const {
  // @@protoc_insertion_point(field_get:errorpb.StaleEpoch.new_regions)
  return new_regions_.Get(index);
}
inline ::metapb::Region* StaleEpoch::mutable_new_regions(int index) {
  // @@protoc_insertion_point(field_mutable:errorpb.StaleEpoch.new_regions)
  return new_regions_.Mutable(index);
}
inline ::metapb::Region* StaleEpoch::add_new_regions() {
  // @@protoc_insertion_point(field_add:errorpb.StaleEpoch.new_regions)
  return new_regions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::metapb::Region >&
StaleEpoch::new_regions() const {
  // @@protoc_insertion_point(field_list:errorpb.StaleEpoch.new_regions)
  return new_regions_;
}
inline ::google::protobuf::RepeatedPtrField< ::metapb::Region >*
StaleEpoch::mutable_new_regions() {
  // @@protoc_insertion_point(field_mutable_list:errorpb.StaleEpoch.new_regions)
  return &new_regions_;
}

// -------------------------------------------------------------------

// ServerIsBusy

// -------------------------------------------------------------------

// StaleCommand

// -------------------------------------------------------------------

// RaftEntryTooLarge

// optional uint64 region_id = 1;
inline bool RaftEntryTooLarge::has_region_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaftEntryTooLarge::set_has_region_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaftEntryTooLarge::clear_has_region_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaftEntryTooLarge::clear_region_id() {
  region_id_ = GOOGLE_ULONGLONG(0);
  clear_has_region_id();
}
inline ::google::protobuf::uint64 RaftEntryTooLarge::region_id() const {
  // @@protoc_insertion_point(field_get:errorpb.RaftEntryTooLarge.region_id)
  return region_id_;
}
inline void RaftEntryTooLarge::set_region_id(::google::protobuf::uint64 value) {
  set_has_region_id();
  region_id_ = value;
  // @@protoc_insertion_point(field_set:errorpb.RaftEntryTooLarge.region_id)
}

// optional uint64 entry_size = 2;
inline bool RaftEntryTooLarge::has_entry_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RaftEntryTooLarge::set_has_entry_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RaftEntryTooLarge::clear_has_entry_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RaftEntryTooLarge::clear_entry_size() {
  entry_size_ = GOOGLE_ULONGLONG(0);
  clear_has_entry_size();
}
inline ::google::protobuf::uint64 RaftEntryTooLarge::entry_size() const {
  // @@protoc_insertion_point(field_get:errorpb.RaftEntryTooLarge.entry_size)
  return entry_size_;
}
inline void RaftEntryTooLarge::set_entry_size(::google::protobuf::uint64 value) {
  set_has_entry_size();
  entry_size_ = value;
  // @@protoc_insertion_point(field_set:errorpb.RaftEntryTooLarge.entry_size)
}

// -------------------------------------------------------------------

// Error

// optional string message = 1;
inline bool Error::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Error::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Error::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Error::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& Error::message() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.message)
  return *message_;
}
inline void Error::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:errorpb.Error.message)
}
inline void Error::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:errorpb.Error.message)
}
inline void Error::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:errorpb.Error.message)
}
inline ::std::string* Error::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:errorpb.Error.message)
  return message_;
}
inline ::std::string* Error::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Error::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.message)
}

// optional .errorpb.NotLeader not_leader = 2;
inline bool Error::has_not_leader() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Error::set_has_not_leader() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Error::clear_has_not_leader() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Error::clear_not_leader() {
  if (not_leader_ != NULL) not_leader_->::errorpb::NotLeader::Clear();
  clear_has_not_leader();
}
inline const ::errorpb::NotLeader& Error::not_leader() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.not_leader)
  return not_leader_ != NULL ? *not_leader_ : *default_instance_->not_leader_;
}
inline ::errorpb::NotLeader* Error::mutable_not_leader() {
  set_has_not_leader();
  if (not_leader_ == NULL) not_leader_ = new ::errorpb::NotLeader;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.not_leader)
  return not_leader_;
}
inline ::errorpb::NotLeader* Error::release_not_leader() {
  clear_has_not_leader();
  ::errorpb::NotLeader* temp = not_leader_;
  not_leader_ = NULL;
  return temp;
}
inline void Error::set_allocated_not_leader(::errorpb::NotLeader* not_leader) {
  delete not_leader_;
  not_leader_ = not_leader;
  if (not_leader) {
    set_has_not_leader();
  } else {
    clear_has_not_leader();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.not_leader)
}

// optional .errorpb.RegionNotFound region_not_found = 3;
inline bool Error::has_region_not_found() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Error::set_has_region_not_found() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Error::clear_has_region_not_found() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Error::clear_region_not_found() {
  if (region_not_found_ != NULL) region_not_found_->::errorpb::RegionNotFound::Clear();
  clear_has_region_not_found();
}
inline const ::errorpb::RegionNotFound& Error::region_not_found() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.region_not_found)
  return region_not_found_ != NULL ? *region_not_found_ : *default_instance_->region_not_found_;
}
inline ::errorpb::RegionNotFound* Error::mutable_region_not_found() {
  set_has_region_not_found();
  if (region_not_found_ == NULL) region_not_found_ = new ::errorpb::RegionNotFound;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.region_not_found)
  return region_not_found_;
}
inline ::errorpb::RegionNotFound* Error::release_region_not_found() {
  clear_has_region_not_found();
  ::errorpb::RegionNotFound* temp = region_not_found_;
  region_not_found_ = NULL;
  return temp;
}
inline void Error::set_allocated_region_not_found(::errorpb::RegionNotFound* region_not_found) {
  delete region_not_found_;
  region_not_found_ = region_not_found;
  if (region_not_found) {
    set_has_region_not_found();
  } else {
    clear_has_region_not_found();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.region_not_found)
}

// optional .errorpb.KeyNotInRegion key_not_in_region = 4;
inline bool Error::has_key_not_in_region() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Error::set_has_key_not_in_region() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Error::clear_has_key_not_in_region() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Error::clear_key_not_in_region() {
  if (key_not_in_region_ != NULL) key_not_in_region_->::errorpb::KeyNotInRegion::Clear();
  clear_has_key_not_in_region();
}
inline const ::errorpb::KeyNotInRegion& Error::key_not_in_region() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.key_not_in_region)
  return key_not_in_region_ != NULL ? *key_not_in_region_ : *default_instance_->key_not_in_region_;
}
inline ::errorpb::KeyNotInRegion* Error::mutable_key_not_in_region() {
  set_has_key_not_in_region();
  if (key_not_in_region_ == NULL) key_not_in_region_ = new ::errorpb::KeyNotInRegion;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.key_not_in_region)
  return key_not_in_region_;
}
inline ::errorpb::KeyNotInRegion* Error::release_key_not_in_region() {
  clear_has_key_not_in_region();
  ::errorpb::KeyNotInRegion* temp = key_not_in_region_;
  key_not_in_region_ = NULL;
  return temp;
}
inline void Error::set_allocated_key_not_in_region(::errorpb::KeyNotInRegion* key_not_in_region) {
  delete key_not_in_region_;
  key_not_in_region_ = key_not_in_region;
  if (key_not_in_region) {
    set_has_key_not_in_region();
  } else {
    clear_has_key_not_in_region();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.key_not_in_region)
}

// optional .errorpb.StaleEpoch stale_epoch = 5;
inline bool Error::has_stale_epoch() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Error::set_has_stale_epoch() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Error::clear_has_stale_epoch() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Error::clear_stale_epoch() {
  if (stale_epoch_ != NULL) stale_epoch_->::errorpb::StaleEpoch::Clear();
  clear_has_stale_epoch();
}
inline const ::errorpb::StaleEpoch& Error::stale_epoch() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.stale_epoch)
  return stale_epoch_ != NULL ? *stale_epoch_ : *default_instance_->stale_epoch_;
}
inline ::errorpb::StaleEpoch* Error::mutable_stale_epoch() {
  set_has_stale_epoch();
  if (stale_epoch_ == NULL) stale_epoch_ = new ::errorpb::StaleEpoch;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.stale_epoch)
  return stale_epoch_;
}
inline ::errorpb::StaleEpoch* Error::release_stale_epoch() {
  clear_has_stale_epoch();
  ::errorpb::StaleEpoch* temp = stale_epoch_;
  stale_epoch_ = NULL;
  return temp;
}
inline void Error::set_allocated_stale_epoch(::errorpb::StaleEpoch* stale_epoch) {
  delete stale_epoch_;
  stale_epoch_ = stale_epoch;
  if (stale_epoch) {
    set_has_stale_epoch();
  } else {
    clear_has_stale_epoch();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.stale_epoch)
}

// optional .errorpb.ServerIsBusy server_is_busy = 6;
inline bool Error::has_server_is_busy() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Error::set_has_server_is_busy() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Error::clear_has_server_is_busy() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Error::clear_server_is_busy() {
  if (server_is_busy_ != NULL) server_is_busy_->::errorpb::ServerIsBusy::Clear();
  clear_has_server_is_busy();
}
inline const ::errorpb::ServerIsBusy& Error::server_is_busy() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.server_is_busy)
  return server_is_busy_ != NULL ? *server_is_busy_ : *default_instance_->server_is_busy_;
}
inline ::errorpb::ServerIsBusy* Error::mutable_server_is_busy() {
  set_has_server_is_busy();
  if (server_is_busy_ == NULL) server_is_busy_ = new ::errorpb::ServerIsBusy;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.server_is_busy)
  return server_is_busy_;
}
inline ::errorpb::ServerIsBusy* Error::release_server_is_busy() {
  clear_has_server_is_busy();
  ::errorpb::ServerIsBusy* temp = server_is_busy_;
  server_is_busy_ = NULL;
  return temp;
}
inline void Error::set_allocated_server_is_busy(::errorpb::ServerIsBusy* server_is_busy) {
  delete server_is_busy_;
  server_is_busy_ = server_is_busy;
  if (server_is_busy) {
    set_has_server_is_busy();
  } else {
    clear_has_server_is_busy();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.server_is_busy)
}

// optional .errorpb.StaleCommand stale_command = 7;
inline bool Error::has_stale_command() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Error::set_has_stale_command() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Error::clear_has_stale_command() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Error::clear_stale_command() {
  if (stale_command_ != NULL) stale_command_->::errorpb::StaleCommand::Clear();
  clear_has_stale_command();
}
inline const ::errorpb::StaleCommand& Error::stale_command() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.stale_command)
  return stale_command_ != NULL ? *stale_command_ : *default_instance_->stale_command_;
}
inline ::errorpb::StaleCommand* Error::mutable_stale_command() {
  set_has_stale_command();
  if (stale_command_ == NULL) stale_command_ = new ::errorpb::StaleCommand;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.stale_command)
  return stale_command_;
}
inline ::errorpb::StaleCommand* Error::release_stale_command() {
  clear_has_stale_command();
  ::errorpb::StaleCommand* temp = stale_command_;
  stale_command_ = NULL;
  return temp;
}
inline void Error::set_allocated_stale_command(::errorpb::StaleCommand* stale_command) {
  delete stale_command_;
  stale_command_ = stale_command;
  if (stale_command) {
    set_has_stale_command();
  } else {
    clear_has_stale_command();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.stale_command)
}

// optional .errorpb.StoreNotMatch store_not_match = 8;
inline bool Error::has_store_not_match() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Error::set_has_store_not_match() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Error::clear_has_store_not_match() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Error::clear_store_not_match() {
  if (store_not_match_ != NULL) store_not_match_->::errorpb::StoreNotMatch::Clear();
  clear_has_store_not_match();
}
inline const ::errorpb::StoreNotMatch& Error::store_not_match() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.store_not_match)
  return store_not_match_ != NULL ? *store_not_match_ : *default_instance_->store_not_match_;
}
inline ::errorpb::StoreNotMatch* Error::mutable_store_not_match() {
  set_has_store_not_match();
  if (store_not_match_ == NULL) store_not_match_ = new ::errorpb::StoreNotMatch;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.store_not_match)
  return store_not_match_;
}
inline ::errorpb::StoreNotMatch* Error::release_store_not_match() {
  clear_has_store_not_match();
  ::errorpb::StoreNotMatch* temp = store_not_match_;
  store_not_match_ = NULL;
  return temp;
}
inline void Error::set_allocated_store_not_match(::errorpb::StoreNotMatch* store_not_match) {
  delete store_not_match_;
  store_not_match_ = store_not_match;
  if (store_not_match) {
    set_has_store_not_match();
  } else {
    clear_has_store_not_match();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.store_not_match)
}

// optional .errorpb.RaftEntryTooLarge raft_entry_too_large = 9;
inline bool Error::has_raft_entry_too_large() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Error::set_has_raft_entry_too_large() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Error::clear_has_raft_entry_too_large() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Error::clear_raft_entry_too_large() {
  if (raft_entry_too_large_ != NULL) raft_entry_too_large_->::errorpb::RaftEntryTooLarge::Clear();
  clear_has_raft_entry_too_large();
}
inline const ::errorpb::RaftEntryTooLarge& Error::raft_entry_too_large() const {
  // @@protoc_insertion_point(field_get:errorpb.Error.raft_entry_too_large)
  return raft_entry_too_large_ != NULL ? *raft_entry_too_large_ : *default_instance_->raft_entry_too_large_;
}
inline ::errorpb::RaftEntryTooLarge* Error::mutable_raft_entry_too_large() {
  set_has_raft_entry_too_large();
  if (raft_entry_too_large_ == NULL) raft_entry_too_large_ = new ::errorpb::RaftEntryTooLarge;
  // @@protoc_insertion_point(field_mutable:errorpb.Error.raft_entry_too_large)
  return raft_entry_too_large_;
}
inline ::errorpb::RaftEntryTooLarge* Error::release_raft_entry_too_large() {
  clear_has_raft_entry_too_large();
  ::errorpb::RaftEntryTooLarge* temp = raft_entry_too_large_;
  raft_entry_too_large_ = NULL;
  return temp;
}
inline void Error::set_allocated_raft_entry_too_large(::errorpb::RaftEntryTooLarge* raft_entry_too_large) {
  delete raft_entry_too_large_;
  raft_entry_too_large_ = raft_entry_too_large;
  if (raft_entry_too_large) {
    set_has_raft_entry_too_large();
  } else {
    clear_has_raft_entry_too_large();
  }
  // @@protoc_insertion_point(field_set_allocated:errorpb.Error.raft_entry_too_large)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace errorpb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_errorpb_2eproto__INCLUDED
