// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgpb.proto

#ifndef PROTOBUF_msgpb_2eproto__INCLUDED
#define PROTOBUF_msgpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "raft_cmdpb.pb.h"
#include "raft_serverpb.pb.h"
#include "kvrpcpb.pb.h"
#include "coprocessor.pb.h"
#include "volume_cmdpb.pb.h"
#include "pdpb.pb.h"
// @@protoc_insertion_point(includes)

namespace msgpb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msgpb_2eproto();
void protobuf_AssignDesc_msgpb_2eproto();
void protobuf_ShutdownFile_msgpb_2eproto();

class Message;

enum MessageType {
  Cmd = 1,
  CmdResp = 2,
  Raft = 3,
  KvReq = 4,
  KvResp = 5,
  CopReq = 6,
  CopResp = 7,
  PdReq = 8,
  PdResp = 9,
  VolumeReq = 10,
  VolumeResp = 11
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = Cmd;
const MessageType MessageType_MAX = VolumeResp;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  Message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .msgpb.MessageType msg_type = 1;
  inline bool has_msg_type() const;
  inline void clear_msg_type();
  static const int kMsgTypeFieldNumber = 1;
  inline ::msgpb::MessageType msg_type() const;
  inline void set_msg_type(::msgpb::MessageType value);

  // optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;
  inline bool has_cmd_req() const;
  inline void clear_cmd_req();
  static const int kCmdReqFieldNumber = 2;
  inline const ::raft_cmdpb::RaftCmdRequest& cmd_req() const;
  inline ::raft_cmdpb::RaftCmdRequest* mutable_cmd_req();
  inline ::raft_cmdpb::RaftCmdRequest* release_cmd_req();
  inline void set_allocated_cmd_req(::raft_cmdpb::RaftCmdRequest* cmd_req);

  // optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;
  inline bool has_cmd_resp() const;
  inline void clear_cmd_resp();
  static const int kCmdRespFieldNumber = 3;
  inline const ::raft_cmdpb::RaftCmdResponse& cmd_resp() const;
  inline ::raft_cmdpb::RaftCmdResponse* mutable_cmd_resp();
  inline ::raft_cmdpb::RaftCmdResponse* release_cmd_resp();
  inline void set_allocated_cmd_resp(::raft_cmdpb::RaftCmdResponse* cmd_resp);

  // optional .raft_serverpb.RaftMessage raft = 4;
  inline bool has_raft() const;
  inline void clear_raft();
  static const int kRaftFieldNumber = 4;
  inline const ::raft_serverpb::RaftMessage& raft() const;
  inline ::raft_serverpb::RaftMessage* mutable_raft();
  inline ::raft_serverpb::RaftMessage* release_raft();
  inline void set_allocated_raft(::raft_serverpb::RaftMessage* raft);

  // optional .kvrpcpb.Request kv_req = 5;
  inline bool has_kv_req() const;
  inline void clear_kv_req();
  static const int kKvReqFieldNumber = 5;
  inline const ::kvrpcpb::Request& kv_req() const;
  inline ::kvrpcpb::Request* mutable_kv_req();
  inline ::kvrpcpb::Request* release_kv_req();
  inline void set_allocated_kv_req(::kvrpcpb::Request* kv_req);

  // optional .kvrpcpb.Response kv_resp = 6;
  inline bool has_kv_resp() const;
  inline void clear_kv_resp();
  static const int kKvRespFieldNumber = 6;
  inline const ::kvrpcpb::Response& kv_resp() const;
  inline ::kvrpcpb::Response* mutable_kv_resp();
  inline ::kvrpcpb::Response* release_kv_resp();
  inline void set_allocated_kv_resp(::kvrpcpb::Response* kv_resp);

  // optional .coprocessor.Request cop_req = 7;
  inline bool has_cop_req() const;
  inline void clear_cop_req();
  static const int kCopReqFieldNumber = 7;
  inline const ::coprocessor::Request& cop_req() const;
  inline ::coprocessor::Request* mutable_cop_req();
  inline ::coprocessor::Request* release_cop_req();
  inline void set_allocated_cop_req(::coprocessor::Request* cop_req);

  // optional .coprocessor.Response cop_resp = 8;
  inline bool has_cop_resp() const;
  inline void clear_cop_resp();
  static const int kCopRespFieldNumber = 8;
  inline const ::coprocessor::Response& cop_resp() const;
  inline ::coprocessor::Response* mutable_cop_resp();
  inline ::coprocessor::Response* release_cop_resp();
  inline void set_allocated_cop_resp(::coprocessor::Response* cop_resp);

  // optional .pdpb.Request pd_req = 9;
  inline bool has_pd_req() const;
  inline void clear_pd_req();
  static const int kPdReqFieldNumber = 9;
  inline const ::pdpb::Request& pd_req() const;
  inline ::pdpb::Request* mutable_pd_req();
  inline ::pdpb::Request* release_pd_req();
  inline void set_allocated_pd_req(::pdpb::Request* pd_req);

  // optional .pdpb.Response pd_resp = 10;
  inline bool has_pd_resp() const;
  inline void clear_pd_resp();
  static const int kPdRespFieldNumber = 10;
  inline const ::pdpb::Response& pd_resp() const;
  inline ::pdpb::Response* mutable_pd_resp();
  inline ::pdpb::Response* release_pd_resp();
  inline void set_allocated_pd_resp(::pdpb::Response* pd_resp);

  // optional .volume_cmdpb.Request volume_req = 11;
  inline bool has_volume_req() const;
  inline void clear_volume_req();
  static const int kVolumeReqFieldNumber = 11;
  inline const ::volume_cmdpb::Request& volume_req() const;
  inline ::volume_cmdpb::Request* mutable_volume_req();
  inline ::volume_cmdpb::Request* release_volume_req();
  inline void set_allocated_volume_req(::volume_cmdpb::Request* volume_req);

  // optional .volume_cmdpb.Response volume_resp = 12;
  inline bool has_volume_resp() const;
  inline void clear_volume_resp();
  static const int kVolumeRespFieldNumber = 12;
  inline const ::volume_cmdpb::Response& volume_resp() const;
  inline ::volume_cmdpb::Response* mutable_volume_resp();
  inline ::volume_cmdpb::Response* release_volume_resp();
  inline void set_allocated_volume_resp(::volume_cmdpb::Response* volume_resp);

  // @@protoc_insertion_point(class_scope:msgpb.Message)
 private:
  inline void set_has_msg_type();
  inline void clear_has_msg_type();
  inline void set_has_cmd_req();
  inline void clear_has_cmd_req();
  inline void set_has_cmd_resp();
  inline void clear_has_cmd_resp();
  inline void set_has_raft();
  inline void clear_has_raft();
  inline void set_has_kv_req();
  inline void clear_has_kv_req();
  inline void set_has_kv_resp();
  inline void clear_has_kv_resp();
  inline void set_has_cop_req();
  inline void clear_has_cop_req();
  inline void set_has_cop_resp();
  inline void clear_has_cop_resp();
  inline void set_has_pd_req();
  inline void clear_has_pd_req();
  inline void set_has_pd_resp();
  inline void clear_has_pd_resp();
  inline void set_has_volume_req();
  inline void clear_has_volume_req();
  inline void set_has_volume_resp();
  inline void clear_has_volume_resp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::raft_cmdpb::RaftCmdRequest* cmd_req_;
  ::raft_cmdpb::RaftCmdResponse* cmd_resp_;
  ::raft_serverpb::RaftMessage* raft_;
  ::kvrpcpb::Request* kv_req_;
  ::kvrpcpb::Response* kv_resp_;
  ::coprocessor::Request* cop_req_;
  ::coprocessor::Response* cop_resp_;
  ::pdpb::Request* pd_req_;
  ::pdpb::Response* pd_resp_;
  ::volume_cmdpb::Request* volume_req_;
  ::volume_cmdpb::Response* volume_resp_;
  int msg_type_;
  friend void  protobuf_AddDesc_msgpb_2eproto();
  friend void protobuf_AssignDesc_msgpb_2eproto();
  friend void protobuf_ShutdownFile_msgpb_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

// Message

// optional .msgpb.MessageType msg_type = 1;
inline bool Message::has_msg_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_msg_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_msg_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_msg_type() {
  msg_type_ = 1;
  clear_has_msg_type();
}
inline ::msgpb::MessageType Message::msg_type() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.msg_type)
  return static_cast< ::msgpb::MessageType >(msg_type_);
}
inline void Message::set_msg_type(::msgpb::MessageType value) {
  assert(::msgpb::MessageType_IsValid(value));
  set_has_msg_type();
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:msgpb.Message.msg_type)
}

// optional .raft_cmdpb.RaftCmdRequest cmd_req = 2;
inline bool Message::has_cmd_req() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_cmd_req() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_cmd_req() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_cmd_req() {
  if (cmd_req_ != NULL) cmd_req_->::raft_cmdpb::RaftCmdRequest::Clear();
  clear_has_cmd_req();
}
inline const ::raft_cmdpb::RaftCmdRequest& Message::cmd_req() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.cmd_req)
  return cmd_req_ != NULL ? *cmd_req_ : *default_instance_->cmd_req_;
}
inline ::raft_cmdpb::RaftCmdRequest* Message::mutable_cmd_req() {
  set_has_cmd_req();
  if (cmd_req_ == NULL) cmd_req_ = new ::raft_cmdpb::RaftCmdRequest;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.cmd_req)
  return cmd_req_;
}
inline ::raft_cmdpb::RaftCmdRequest* Message::release_cmd_req() {
  clear_has_cmd_req();
  ::raft_cmdpb::RaftCmdRequest* temp = cmd_req_;
  cmd_req_ = NULL;
  return temp;
}
inline void Message::set_allocated_cmd_req(::raft_cmdpb::RaftCmdRequest* cmd_req) {
  delete cmd_req_;
  cmd_req_ = cmd_req;
  if (cmd_req) {
    set_has_cmd_req();
  } else {
    clear_has_cmd_req();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.cmd_req)
}

// optional .raft_cmdpb.RaftCmdResponse cmd_resp = 3;
inline bool Message::has_cmd_resp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_cmd_resp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_cmd_resp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_cmd_resp() {
  if (cmd_resp_ != NULL) cmd_resp_->::raft_cmdpb::RaftCmdResponse::Clear();
  clear_has_cmd_resp();
}
inline const ::raft_cmdpb::RaftCmdResponse& Message::cmd_resp() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.cmd_resp)
  return cmd_resp_ != NULL ? *cmd_resp_ : *default_instance_->cmd_resp_;
}
inline ::raft_cmdpb::RaftCmdResponse* Message::mutable_cmd_resp() {
  set_has_cmd_resp();
  if (cmd_resp_ == NULL) cmd_resp_ = new ::raft_cmdpb::RaftCmdResponse;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.cmd_resp)
  return cmd_resp_;
}
inline ::raft_cmdpb::RaftCmdResponse* Message::release_cmd_resp() {
  clear_has_cmd_resp();
  ::raft_cmdpb::RaftCmdResponse* temp = cmd_resp_;
  cmd_resp_ = NULL;
  return temp;
}
inline void Message::set_allocated_cmd_resp(::raft_cmdpb::RaftCmdResponse* cmd_resp) {
  delete cmd_resp_;
  cmd_resp_ = cmd_resp;
  if (cmd_resp) {
    set_has_cmd_resp();
  } else {
    clear_has_cmd_resp();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.cmd_resp)
}

// optional .raft_serverpb.RaftMessage raft = 4;
inline bool Message::has_raft() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_raft() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_raft() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_raft() {
  if (raft_ != NULL) raft_->::raft_serverpb::RaftMessage::Clear();
  clear_has_raft();
}
inline const ::raft_serverpb::RaftMessage& Message::raft() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.raft)
  return raft_ != NULL ? *raft_ : *default_instance_->raft_;
}
inline ::raft_serverpb::RaftMessage* Message::mutable_raft() {
  set_has_raft();
  if (raft_ == NULL) raft_ = new ::raft_serverpb::RaftMessage;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.raft)
  return raft_;
}
inline ::raft_serverpb::RaftMessage* Message::release_raft() {
  clear_has_raft();
  ::raft_serverpb::RaftMessage* temp = raft_;
  raft_ = NULL;
  return temp;
}
inline void Message::set_allocated_raft(::raft_serverpb::RaftMessage* raft) {
  delete raft_;
  raft_ = raft;
  if (raft) {
    set_has_raft();
  } else {
    clear_has_raft();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.raft)
}

// optional .kvrpcpb.Request kv_req = 5;
inline bool Message::has_kv_req() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_kv_req() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_kv_req() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_kv_req() {
  if (kv_req_ != NULL) kv_req_->::kvrpcpb::Request::Clear();
  clear_has_kv_req();
}
inline const ::kvrpcpb::Request& Message::kv_req() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.kv_req)
  return kv_req_ != NULL ? *kv_req_ : *default_instance_->kv_req_;
}
inline ::kvrpcpb::Request* Message::mutable_kv_req() {
  set_has_kv_req();
  if (kv_req_ == NULL) kv_req_ = new ::kvrpcpb::Request;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.kv_req)
  return kv_req_;
}
inline ::kvrpcpb::Request* Message::release_kv_req() {
  clear_has_kv_req();
  ::kvrpcpb::Request* temp = kv_req_;
  kv_req_ = NULL;
  return temp;
}
inline void Message::set_allocated_kv_req(::kvrpcpb::Request* kv_req) {
  delete kv_req_;
  kv_req_ = kv_req;
  if (kv_req) {
    set_has_kv_req();
  } else {
    clear_has_kv_req();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.kv_req)
}

// optional .kvrpcpb.Response kv_resp = 6;
inline bool Message::has_kv_resp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_kv_resp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_kv_resp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_kv_resp() {
  if (kv_resp_ != NULL) kv_resp_->::kvrpcpb::Response::Clear();
  clear_has_kv_resp();
}
inline const ::kvrpcpb::Response& Message::kv_resp() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.kv_resp)
  return kv_resp_ != NULL ? *kv_resp_ : *default_instance_->kv_resp_;
}
inline ::kvrpcpb::Response* Message::mutable_kv_resp() {
  set_has_kv_resp();
  if (kv_resp_ == NULL) kv_resp_ = new ::kvrpcpb::Response;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.kv_resp)
  return kv_resp_;
}
inline ::kvrpcpb::Response* Message::release_kv_resp() {
  clear_has_kv_resp();
  ::kvrpcpb::Response* temp = kv_resp_;
  kv_resp_ = NULL;
  return temp;
}
inline void Message::set_allocated_kv_resp(::kvrpcpb::Response* kv_resp) {
  delete kv_resp_;
  kv_resp_ = kv_resp;
  if (kv_resp) {
    set_has_kv_resp();
  } else {
    clear_has_kv_resp();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.kv_resp)
}

// optional .coprocessor.Request cop_req = 7;
inline bool Message::has_cop_req() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Message::set_has_cop_req() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Message::clear_has_cop_req() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Message::clear_cop_req() {
  if (cop_req_ != NULL) cop_req_->::coprocessor::Request::Clear();
  clear_has_cop_req();
}
inline const ::coprocessor::Request& Message::cop_req() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.cop_req)
  return cop_req_ != NULL ? *cop_req_ : *default_instance_->cop_req_;
}
inline ::coprocessor::Request* Message::mutable_cop_req() {
  set_has_cop_req();
  if (cop_req_ == NULL) cop_req_ = new ::coprocessor::Request;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.cop_req)
  return cop_req_;
}
inline ::coprocessor::Request* Message::release_cop_req() {
  clear_has_cop_req();
  ::coprocessor::Request* temp = cop_req_;
  cop_req_ = NULL;
  return temp;
}
inline void Message::set_allocated_cop_req(::coprocessor::Request* cop_req) {
  delete cop_req_;
  cop_req_ = cop_req;
  if (cop_req) {
    set_has_cop_req();
  } else {
    clear_has_cop_req();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.cop_req)
}

// optional .coprocessor.Response cop_resp = 8;
inline bool Message::has_cop_resp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Message::set_has_cop_resp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Message::clear_has_cop_resp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Message::clear_cop_resp() {
  if (cop_resp_ != NULL) cop_resp_->::coprocessor::Response::Clear();
  clear_has_cop_resp();
}
inline const ::coprocessor::Response& Message::cop_resp() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.cop_resp)
  return cop_resp_ != NULL ? *cop_resp_ : *default_instance_->cop_resp_;
}
inline ::coprocessor::Response* Message::mutable_cop_resp() {
  set_has_cop_resp();
  if (cop_resp_ == NULL) cop_resp_ = new ::coprocessor::Response;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.cop_resp)
  return cop_resp_;
}
inline ::coprocessor::Response* Message::release_cop_resp() {
  clear_has_cop_resp();
  ::coprocessor::Response* temp = cop_resp_;
  cop_resp_ = NULL;
  return temp;
}
inline void Message::set_allocated_cop_resp(::coprocessor::Response* cop_resp) {
  delete cop_resp_;
  cop_resp_ = cop_resp;
  if (cop_resp) {
    set_has_cop_resp();
  } else {
    clear_has_cop_resp();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.cop_resp)
}

// optional .pdpb.Request pd_req = 9;
inline bool Message::has_pd_req() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Message::set_has_pd_req() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Message::clear_has_pd_req() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Message::clear_pd_req() {
  if (pd_req_ != NULL) pd_req_->::pdpb::Request::Clear();
  clear_has_pd_req();
}
inline const ::pdpb::Request& Message::pd_req() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.pd_req)
  return pd_req_ != NULL ? *pd_req_ : *default_instance_->pd_req_;
}
inline ::pdpb::Request* Message::mutable_pd_req() {
  set_has_pd_req();
  if (pd_req_ == NULL) pd_req_ = new ::pdpb::Request;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.pd_req)
  return pd_req_;
}
inline ::pdpb::Request* Message::release_pd_req() {
  clear_has_pd_req();
  ::pdpb::Request* temp = pd_req_;
  pd_req_ = NULL;
  return temp;
}
inline void Message::set_allocated_pd_req(::pdpb::Request* pd_req) {
  delete pd_req_;
  pd_req_ = pd_req;
  if (pd_req) {
    set_has_pd_req();
  } else {
    clear_has_pd_req();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.pd_req)
}

// optional .pdpb.Response pd_resp = 10;
inline bool Message::has_pd_resp() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Message::set_has_pd_resp() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Message::clear_has_pd_resp() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Message::clear_pd_resp() {
  if (pd_resp_ != NULL) pd_resp_->::pdpb::Response::Clear();
  clear_has_pd_resp();
}
inline const ::pdpb::Response& Message::pd_resp() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.pd_resp)
  return pd_resp_ != NULL ? *pd_resp_ : *default_instance_->pd_resp_;
}
inline ::pdpb::Response* Message::mutable_pd_resp() {
  set_has_pd_resp();
  if (pd_resp_ == NULL) pd_resp_ = new ::pdpb::Response;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.pd_resp)
  return pd_resp_;
}
inline ::pdpb::Response* Message::release_pd_resp() {
  clear_has_pd_resp();
  ::pdpb::Response* temp = pd_resp_;
  pd_resp_ = NULL;
  return temp;
}
inline void Message::set_allocated_pd_resp(::pdpb::Response* pd_resp) {
  delete pd_resp_;
  pd_resp_ = pd_resp;
  if (pd_resp) {
    set_has_pd_resp();
  } else {
    clear_has_pd_resp();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.pd_resp)
}

// optional .volume_cmdpb.Request volume_req = 11;
inline bool Message::has_volume_req() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Message::set_has_volume_req() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Message::clear_has_volume_req() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Message::clear_volume_req() {
  if (volume_req_ != NULL) volume_req_->::volume_cmdpb::Request::Clear();
  clear_has_volume_req();
}
inline const ::volume_cmdpb::Request& Message::volume_req() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.volume_req)
  return volume_req_ != NULL ? *volume_req_ : *default_instance_->volume_req_;
}
inline ::volume_cmdpb::Request* Message::mutable_volume_req() {
  set_has_volume_req();
  if (volume_req_ == NULL) volume_req_ = new ::volume_cmdpb::Request;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.volume_req)
  return volume_req_;
}
inline ::volume_cmdpb::Request* Message::release_volume_req() {
  clear_has_volume_req();
  ::volume_cmdpb::Request* temp = volume_req_;
  volume_req_ = NULL;
  return temp;
}
inline void Message::set_allocated_volume_req(::volume_cmdpb::Request* volume_req) {
  delete volume_req_;
  volume_req_ = volume_req;
  if (volume_req) {
    set_has_volume_req();
  } else {
    clear_has_volume_req();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.volume_req)
}

// optional .volume_cmdpb.Response volume_resp = 12;
inline bool Message::has_volume_resp() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Message::set_has_volume_resp() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Message::clear_has_volume_resp() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Message::clear_volume_resp() {
  if (volume_resp_ != NULL) volume_resp_->::volume_cmdpb::Response::Clear();
  clear_has_volume_resp();
}
inline const ::volume_cmdpb::Response& Message::volume_resp() const {
  // @@protoc_insertion_point(field_get:msgpb.Message.volume_resp)
  return volume_resp_ != NULL ? *volume_resp_ : *default_instance_->volume_resp_;
}
inline ::volume_cmdpb::Response* Message::mutable_volume_resp() {
  set_has_volume_resp();
  if (volume_resp_ == NULL) volume_resp_ = new ::volume_cmdpb::Response;
  // @@protoc_insertion_point(field_mutable:msgpb.Message.volume_resp)
  return volume_resp_;
}
inline ::volume_cmdpb::Response* Message::release_volume_resp() {
  clear_has_volume_resp();
  ::volume_cmdpb::Response* temp = volume_resp_;
  volume_resp_ = NULL;
  return temp;
}
inline void Message::set_allocated_volume_resp(::volume_cmdpb::Response* volume_resp) {
  delete volume_resp_;
  volume_resp_ = volume_resp;
  if (volume_resp) {
    set_has_volume_resp();
  } else {
    clear_has_volume_resp();
  }
  // @@protoc_insertion_point(field_set_allocated:msgpb.Message.volume_resp)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgpb

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::msgpb::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msgpb::MessageType>() {
  return ::msgpb::MessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgpb_2eproto__INCLUDED
